import { Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Shpotti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Text fontSize="3xl">Shpotti</Text>
        <h1 className="text-3xl font-bold">Hello world!</h1>
      </main>
    </>
  );
};

export default Home;
